# File: Dockerfile.api
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

# Copy csproj and restore dependencies
COPY EmployeeFormApi/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY EmployeeFormApi/ ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "EmployeeFormApi.dll"]
